-- Table des produits
CREATE TABLE IF NOT EXISTS public.products (
    id TEXT PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    name_ar TEXT,
    tagline TEXT,
    tagline_ar TEXT,
    description TEXT,
    description_ar TEXT,
    price NUMERIC NOT NULL,
    currency TEXT DEFAULT 'DZD',
    size TEXT,
    category TEXT NOT NULL,
    badge TEXT,
    images TEXT[] DEFAULT '{}',
    hero_image TEXT,
    top_notes JSONB DEFAULT '[]',
    heart_notes JSONB DEFAULT '[]',
    base_notes JSONB DEFAULT '[]',
    ingredients TEXT,
    in_stock BOOLEAN DEFAULT true,
    rating NUMERIC DEFAULT 5.0,
    review_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insérer les produits initiaux
INSERT INTO public.products (
    id, slug, name, name_ar, tagline, tagline_ar, description, description_ar, 
    price, currency, size, category, badge, images, hero_image, 
    top_notes, heart_notes, base_notes, ingredients, in_stock, rating, review_count
) VALUES 
(
    'chogam-100ml',
    'chogam',
    'Chogam',
    'شوجام',
    'Eau de Parfum Pour Homme — 100ml',
    'او دو بارفان بور أوم — 100 مل',
    'Chogam est la fragrance signature audacieuse — conçue pour l''homme qui s''impose dans chaque pièce. Une ouverture électrisante de bergamote et poivre noir laisse place à un cœur puissant de oud fumé et de cuir, avant de se poser sur une base riche et durable d''ambre, de musc et de bois de santal.',
    'شوجام هو التوقيع الجريء — عطر للرجل الذي يُسيطر على كل غرفة يدخلها.',
    3500,
    'DZD',
    '100ml / 3.4 FL.OZ.',
    'pour homme',
    'bestSeller',
    ARRAY['/products/bravento/bravento-hero-marble.png', '/products/bravento/bravento-box-bottle-duo.png', '/products/bravento/bravento-cap-macro.png', '/products/bravento/bravento-lifestyle-smoke.png'],
    '/products/bravento/bravento-hero-marble.png',
    '[{"name": "Bergamote", "icon": "🍋"}, {"name": "Poivre Noir", "icon": "🌶"}, {"name": "Cardamome", "icon": "🌿"}]'::jsonb,
    '[{"name": "Oud", "icon": "🪵"}, {"name": "Cuir", "icon": "🔶"}, {"name": "Vétiver", "icon": "🌾"}]'::jsonb,
    '[{"name": "Ambre", "icon": "✨"}, {"name": "Musc", "icon": "🌙"}, {"name": "Bois de Santal", "icon": "🪵"}]'::jsonb,
    'Alcohol Denat., Fragrance (Parfum), Aqua (Water), Benzyl Benzoate, Linalool, Limonene, Coumarin, Benzyl Salicylate, Citronellol, Alpha-Isomethyl Ionone.',
    true,
    4.9,
    247
),
(
    'nuit-orientale-100ml',
    'nuit-orientale',
    'Nuit Orientale',
    'نوي أورونتال',
    'Eau de Parfum — 100ml',
    'او دو بارفان — 100 مل',
    'Un voyage oriental sensuel à travers la rose sombre, le safran et la vanille chaude. Un parfum du soir d''un mystère rare.',
    'رحلة شرقية حسية عبر الوردة الداكنة والزعفران والفانيليا الدافئة.',
    3200,
    'DZD',
    '100ml / 3.4 FL.OZ.',
    'unisex',
    'newArrival',
    ARRAY['/products/bravento/bravento-ingredients.png'],
    '/products/bravento/bravento-ingredients.png',
    '[{"name": "Safran", "icon": "🌸"}, {"name": "Rose", "icon": "🌹"}, {"name": "Poivre Rose", "icon": "🌺"}]'::jsonb,
    '[{"name": "Oud", "icon": "🪵"}, {"name": "Jasmin", "icon": "🌼"}, {"name": "Patchouli", "icon": "🌿"}]'::jsonb,
    '[{"name": "Vanille", "icon": "🍦"}, {"name": "Ambre", "icon": "✨"}, {"name": "Musc", "icon": "🌙"}]'::jsonb,
    'Alcohol Denat., Fragrance (Parfum), Aqua (Water), Linalool, Limonene, Geraniol, Citronellol, Eugenol.',
    true,
    4.7,
    89
),
(
    'azur-blanc-100ml',
    'azur-blanc',
    'Azur Blanc',
    'أزور بلان',
    'Eau de Parfum Pour Femme — 100ml',
    'او دو بارفان بور فام — 100 مل',
    'Une fragrance florale aquatique lumineuse inspirée de la côte méditerranéenne — néroli frais, pivoine blanche et bois de cèdre.',
    'عطر مائي زهري مشرق مستوحى من الساحل المتوسطي.',
    2900,
    'DZD',
    '100ml / 3.4 FL.OZ.',
    'pour femme',
    NULL,
    ARRAY['/products/bravento/bravento-lifestyle-smoke.png'],
    '/products/bravento/bravento-lifestyle-smoke.png',
    '[{"name": "Néroli", "icon": "🌸"}, {"name": "Citron", "icon": "🍋"}, {"name": "Sel Marin", "icon": "💧"}]'::jsonb,
    '[{"name": "Pivoine Blanche", "icon": "🌼"}, {"name": "Iris", "icon": "🌷"}, {"name": "Jasmin", "icon": "🌺"}]'::jsonb,
    '[{"name": "Cèdre", "icon": "🌲"}, {"name": "Musc Blanc", "icon": "🌙"}, {"name": "Ambrette", "icon": "✨"}]'::jsonb,
    'Alcohol Denat., Fragrance (Parfum), Aqua (Water), Linalool, Citronellol, Geraniol, Benzyl Alcohol.',
    true,
    4.6,
    134
),
(
    'roi-desert-100ml',
    'roi-desert',
    'Roi du Désert',
    'روا دو ديزير',
    'Eau de Parfum Pour Homme — 100ml',
    'او دو بارفان بور أوم — 100 مل',
    'Inspiré du Sahara algérien — les dunes infinies, le vent chaud, la liberté sauvage. Encens fumé, bois secs et résines précieuses.',
    'مستوحى من الصحراء الجزائرية — الكثبان اللانهائية، الريح الدافئة.',
    3800,
    'DZD',
    '100ml / 3.4 FL.OZ.',
    'pour homme',
    'limited',
    ARRAY['/products/bravento/bravento-box-bottle-duo.png'],
    '/products/bravento/bravento-box-bottle-duo.png',
    '[{"name": "Encens", "icon": "🕯"}, {"name": "Cardamome", "icon": "🌿"}, {"name": "Pamplemousse", "icon": "🍊"}]'::jsonb,
    '[{"name": "Oud", "icon": "🪵"}, {"name": "Myrrhe", "icon": "🌑"}, {"name": "Cuir", "icon": "🔶"}]'::jsonb,
    '[{"name": "Benjoin", "icon": "💫"}, {"name": "Labdanum", "icon": "🌿"}, {"name": "Ambre", "icon": "✨"}]'::jsonb,
    'Alcohol Denat., Fragrance (Parfum), Aqua (Water), Benzyl Benzoate, Eugenol, Linalool, Limonene, Coumarin.',
    true,
    4.8,
    56
)
ON CONFLICT (id) DO NOTHING;
